### ISSUE TITLE
DBM status bar times errors spamming me

### ISSUE THREAD

**Issue by Zehdah** [DeadlyBossMods/DeadlyBossMods#511] opened 2021-02-21 21:01 UTC
I have the latest versions of DBM and DBM PvP mods and I'm being spammed with these errors, which I will copy below. I can't seem to reproduce them, it just happens randomly and pops up in the middle of my screen, sometimes 100s of times before it goes away. I've tried reinstalling the mods and disabling all other mods to test if it was that but the issue still remains. Anyway to fix it? 

The errors:
Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_8:SetPoint.
Time: Sun Feb 21 20:42:44 2021
Count: 1
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_8:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1513: in function `SetPosition'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:812: in function <Interface\AddOns\DBM-StatusBarTimers\DBT.lua:740>
[string "=[C]"]: in function `CreateBar'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4061: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:892: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:879>

Locals: 

Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DBT_Bar_1:SetPoint.
Time: Sun Feb 21 19:12:39 2021
Count: 1
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DBT_Bar_1:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1513: in function `SetPosition'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:526: in function `Append'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:812: in function <Interface\AddOns\DBM-StatusBarTimers\DBT.lua:740>
[string "=[C]"]: in function `CreateBar'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:11000: in function `Start'
[string "@Interface\AddOns\DBM-Party-Shadowlands\TheNecroticWake\Nalthor.lua"]:64: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:892: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:879>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:892: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:879>

Locals: 

Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1520: attempt to perform arithmetic on a nil value
Time: Sun Feb 21 19:13:23 2021
Count: 544
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1520: attempt to perform arithmetic on a nil value
[string "=[C]"]: ?
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1520: in function `MoveToNextPosition'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:559: in function `Remove'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1218: in function `RemoveFromList'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1158: in function <Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1005>
[string "=[C]"]: in function `Update'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1610: in function <Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1604>

Locals:

**Comment by MysticalOS** [comment] 2021-02-21 21:04
duplicate of #506

**Closed by MysticalOS** 2021-02-21 21:04 UTC

**Comment by MysticalOS** [comment] 2021-02-21 21:56
I'm still 100% confident some 3rd party mod is doing some aggressive broken tainting of DBM code. I close issue cause i want you to post in other open issue but please list ALL of your mods

**Comment by Zehdah** [comment] 2021-02-22 08:40
> I'm still 100% confident some 3rd party mod is doing some aggressive broken tainting of DBM code. I close issue cause i want you to post in other open issue but please list ALL of your mods

No worries, I should have checked, sorry. Here's a list of all my mods:
DBM
DBM PvP Mods
Advanced Interface Options
Azeroth Auto Pilot
Battleground Enemies
Big Debuffs
Classic Floating Combat Text
Details!
Gladius
Leatrix Plus
OmniCC
Omnibar
Threat Plates
Shadow and Light
Weak Auras

**Comment by MysticalOS** [comment] 2021-02-22 08:44
please repost it in https://github.com/DeadlyBossMods/DeadlyBossMods/issues/506

i want to aggregate all the comments to a single issue.
