### ISSUE TITLE
WoW Classic Era Version 1.15.1 - DBM not working for Raid bossed

### ISSUE THREAD

**Issue by maximus210793** [DeadlyBossMods/DeadlyBossMods#1006] opened 2024-03-20 15:05 UTC
Hi,
the last version is no longer working for any raid bosses, so no warnings etc. are displayed.
Under settings -> "Raids" everything is empty.
Thanks for fixing it.

**Comment by MysticalOS** [comment] 2024-03-20 15:07
duplicate of https://github.com/DeadlyBossMods/DBM-BCVanilla/issues/108

**Closed by MysticalOS** 2024-03-20 15:07 UTC
