### ISSUE TITLE
LUA Error anytime I get a whisper

### ISSUE THREAD

**Issue by Seeyen** [DeadlyBossMods/DeadlyBossMods#1342] opened 2024-10-24 20:57 UTC
Message: Interface/AddOns/DBM-Core/DBM-Core.lua:678: 'for' limit must be a number
Time: Thu Oct 24 15:55:18 2024
Count: 1
Stack: Interface/AddOns/DBM-Core/DBM-Core.lua:678: 'for' limit must be a number
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:678: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:636>
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:7191: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:7189>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:1082: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:1069>

Locals: sender = "Dalastish"
checkFriends = true
checkGuild = true
filterRaid = true
isRealIdMessage = false
totalMembers = 961
_ = 18
numOnlineAndMobileMembers = nil
scanTotal = nil
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = "BSAp"
(*temporary) = <table> {
 isFriend = true
 isDND = false
 isFavorite = false
 gameAccountInfo = <table> {
 }
 accountName = "Kp85k"
 battleTag = "Swing#11842"
 note = ""
 rafLinkType = 0
 bnetAccountID = 148
 appearOffline = false
 customMessage = ""
 lastOnlineTime = 1729675050
 customMessageTime = 1612629569
 isAFK = false
 isBattleTagFriend = true
}
(*temporary) = <table> {
 isGameAFK = true
 clientProgram = "BSAp"
 richPresence = ""
 isGameBusy = false
 gameAccountID = 224
 isInCurrentRegion = true
 regionID = 1
 hasFocus = true
 canSummon = false
 isOnline = true
}
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
DBM = <table> {
 DungeonMusic = <table> {
 }
 ReleaseRevision = 20241022000000
 TaintedByTests = false
 Arrow = <table> {
 }
 RangeCheck = <table> {
 }
 Test = <table> {
 }
 Voices = <table> {
 }
 BattleMusic = <table> {
 }
 InfoFrame = <table> {
 }
 Flash = <table> {
 }
 ModLists = <table> {
 }
 Difficulties = <table> {
 }
 Music = <table> {
 }
 classicSubVersion = 0
 HighestRelease = 20241022000000
 registeredUnitEvents = <table> {
 }
 VoiceVersions = <table> {
 }
 AddOns = <table> {
 }
 Options = <table> {
 }
 Revision = 20241022110915
 shortTermRegisterEvents = <table> {
 }
 Defeat = <table> {
 }
 DefaultOptions = <table> {
 }
 Victory = <table> {
 }
 Counts = <table> {
 }
 Nameplate = <table> {
 }
 HudMap = <table> {
 }
 DisplayVersion = "11.0.23"
 Mods = <table> {
 }
}

**Comment by Seeyen** [comment] 2024-10-24 21:23
Used Curse and deleted all DBM addons. Re-installed and still bad. May have to go to bigwigs.

**Comment by MysticalOS** [comment] 2024-10-24 22:59
Duplicate of https://github.com/DeadlyBossMods/DeadlyBossMods/issues/1341

was fixed two days ago and will get a release out shortly. Blizzard changed an api in patch that was undocumented and not caught on PTR cause it requires you to be in a guild to detect (and PTR testing was not done guilded)

**Closed by MysticalOS** 2024-10-24 22:59 UTC
