### ISSUE TITLE
DBM-Classic tagged for retail

### ISSUE THREAD

**Issue by cfmcghee** [DeadlyBossMods/DeadlyBossMods#94] opened 2019-11-30 00:53 UTC
Updated my RETAIL-DBM addon as suggested by the Curse client

Logged into RETAIL WoW and upon load-in the addon notified me that I had the CLASSIC version installed.

**Comment by MysticalOS** [comment] 2019-11-30 01:13
Duplicate of https://github.com/DeadlyBossMods/DeadlyBossMods/issues/74

Not a DBM issue, a twitch client bug.

**Closed by MysticalOS** 2019-11-30 01:13 UTC
Labels: duplicate, invalid, wontfix

**Comment by shhhhhwinky** [comment] 2019-12-01 06:39
i also had this issue. fixed mine by deleting the dbm-classic folder out of my addons file (as i dont play classic) then installing the lastest DBM alpha version 8.2.29-12-g62025ad that was released 11/29/19 (found under the "versions" option on twitch). my game seems to be functioning fine now. it wasnt working properly before (couldnt hear sound or notifications, dbm wasnt working at all, etc) because my wow client was stating the addon was too out of date. pretty sure just installing the new alpha version will also work, if you are a classic user.
