### ISSUE TITLE
Countdown sound overlap issue

### ISSUE THREAD

**Issue by Wyrade** [DeadlyBossMods/DeadlyBossMods#33] opened 2019-07-09 05:17 UTC
**Describe the bug**
During darkmoon faire fire ring challange the coundown sound doesn't reset when I go through a new circle as it should. It plays the "five-four-..." countdown for the first ring even if I went through another one already. And overlaps the countdown of all rings.
It worked properly a few months ago at around the start of bfa (?) when i last played this minigame. Meaning when it started the "five" countdown, if I went through another ring it stopped abruptly, and only played the sound for the last one, actually accurately indicating the time left of flying.

**Do you have an error log of what happened?**
No errors afaik. Didn't check extensively.
If others don't normally have this issue, please say so, and I'll try to hunt down what I messed up in my wow folder somehow.

**To Reproduce**
1. Go to Ziggie Sparks in the darkmoon faire, and start a firebird challenge.
2. Go through more than one rings, and hear the countdown messed up.

**Screenshots**
N/A

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but I disabled elvui and weakauras2.

**Which version of DeadlyBossMods are you using?**
8.2.2 (2019/07/07 01:22:51) according to ingame.

**Was it working in a previous version? If yes, which was the last good one?**
Yes, no idea what version of dbm it was, and wow changed a lot since too, it having been at around the start of bfa (?).

**Additional context**
((Damn github somehow disappeared all i wrote the first time, changing it to a blank template right before i posted, after I wrote a title....))

**Comment by MysticalOS** [comment] 2019-07-09 07:07
Duplicate of #32

**Closed by MysticalOS** 2019-07-09 07:07 UTC
Labels: 🐛 Bug
