### ISSUE TITLE
"Status Bar Timers" throwing random errors in rated BGs and on council

### ISSUE THREAD

**Issue by TheCheat54** [DeadlyBossMods/DeadlyBossMods#506] opened 2021-02-06 21:30 UTC
While doing rated BGs today, I started getting random LUA errors that look like below. It causes the timers for PvP mods to eventually become corrupt and not always appear. I have to reload UI while in the BG in order to correct the problem.

Not sure which module it's specifically related to but my Core version is 9.0.19-30-g74e6e8c and DBT.lua has a modified date of 2/5 5:58 PM CST.

Date: 2021-02-06 15:08:26
ID: 3
Error occured in: Global
Count: 480
Message: ..\AddOns\DBM-StatusBarTimers\DBT.lua line 1562:
   Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_2:SetPoint.
Debug:
   [string "=[C]"]: SetPoint()
   [string "@DBM-StatusBarTimers\DBT.lua"]:1562: Enlarge()
   [string "@DBM-StatusBarTimers\DBT.lua"]:1160: Update()
   [string "@DBM-StatusBarTimers\DBT.lua"]:1611:
      DBM-StatusBarTimers\DBT.lua:1605
Locals:
(*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0

**Comment by amk0** [comment] 2021-02-24 16:49
Keep getting that too on every single BG. The first one works fine, after that only a /reload inside the subsequent BGs will make it stop appearing until the next one.

Edit: Happens on all BGs with timers, normal or rated.

**Comment by MysticalOS** [comment] 2021-02-24 16:51
Please post a full list of all your addons

**Comment by QartemisT** [comment] 2021-02-24 16:52
Also make sure you are running r116 of PvP.

**Comment by TheCheat54** [comment] 2021-02-24 16:58
My addon list below. Last occurrence of the error was 2/18 which would have been the night I did rated BGs with the guild. Didn't get any in randoms since r116 two days ago but those were only epic BGs.

`  Swatter, v7.3.1 (<%codename%>)
  AdvancedInterfaceOptions, v1.4.3
  AngryKeystones, v
  AstralKeys, v3.38
  AtlasLoot, vr4839
  AtlasLootBattleforAzeroth, vr4839
  AtlasLootBurningCrusade, vr4839
  AtlasLootCataclysm, vr4839
  AtlasLootClassic, vr4839
  AtlasLootLegion, vr4839
  AtlasLootMistsofPandaria, vr4839
  AtlasLootWarlordsofDraenor, vr4839
  AtlasLootWrathoftheLichKing, vr4839
  AzeriteTooltip, v2.0.9
  BattleGroundEnemies, v9.0.2.7-9-geba77fd
  BattlePetBreedID, vv1.17.5
  BetterPowerBarAlt, v1.5.6
  DBMCore, v9.0.21-5-gfc249c4
  DBMCountPackHotS, v1.7.10
  DBMCountPackOverwatch, v1.4.14
  DBMDefaultSkin, v
  DBMPartyCataclysm, vr23
  DBMStatusBarTimers, v
  DBMWorldEvents, v
  DejaCharacterStats, v900r2
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ExRT, v4460
  FishingBuddy, v1.15
  FlaresThatWork, vr47
  Gladius, v7.0.3
  GreatVault, v1.04
  Grid2, v1.1.17-beta
  Grid2LDB, v1.1.17-beta
  Grid2RaidDebuffs, v1.1.17-beta
  GryphonsGTFO, v
  GuildCheck, vv 2.5.1
  HandyNotes, vv1.6.1
  HandyNotesBattleForAzeroth, v4
  HandyNotesBattleForAzerothTreasures, vv16
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesShadowlands, v28
  HandyNotesWarfrontRares, v0.5.0
  HiddenArtifactTracker, v
  InFlightLoad, v9.0.002
  InstanceAchievementTracker, v3.18.0
  KuiMedia, v
  KuiNameplates, v2.27.2
  KuiNameplatesCore, v
  LoggerHead, v199
  MoveAnything, v18.0.5
  MythicDungeonTools, v3.4.7
  NoThunderTotemMap, v2.0
  NPCScan, v9.0.1.3
  NugComboBar, v9.0.9
  Omen, v3.2.4
  OmniCC, v9.0.5
  ParagonReputation, v1.32
  Paste, v1.4.10
  PetCaught, v1.1
  Prat30, v3.9.1
  Prat30Libraries, v
  Quartz, v3.6.2
  RaiderIO, v9.0.2 (v202102220658)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  Rarity, v1.0 (r705-alpha-1)
  RarityOptions, v
  Rematch, v4.11.11
  RSA, vr542-Release
  RSAWarrior, v
  SavedInstances, v9.0.5-34-gf49ad42
  sct, v8.1
  SexyMap, vv9.0.16
  ShadowedUnitFrames, vv4.3.4
  SharedMedia, v3.1.0-194
  SharedMediaAdditionalFonts, v9.0.2
  Simulationcraft, v9.0.2-15
  SlideBar, v7.3.1 (<%codename%>)
  StatBlockMemory, v
  Titan, v5.20.2.90002
  TitanBag, v5.20.2.90002
  TitanClock, v5.20.2.90002
  TitanGold, v5.20.2.90002
  TitanLocation, v5.20.2.90002
  TitanLootType, v5.20.2.90002
  TitanPerformance, v5.20.2.90002
  TitanRepair, v5.20.2.90002
  TitanSpeed, v9.0.1
  TitanVolume, v5.20.2.90002
  TitanXP, v5.20.2.90002
  TomTom, vv90002-1.2.0
  VenturePlan, v4.11a
  WeakAuras, v3.1.9-28-g99622d5
  WorldBossTimers, vv1.5.2
  WorldQuestTracker, v`

**Comment by amk0** [comment] 2021-02-24 20:11
I get 3 different reports. Pasting em here then providing the add on list.

Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1511: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_2:SetPoint.
Time: Wed Feb 24 20:12:19 2021
Count: 1
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1511: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1511: in function `SetPosition'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:812: in function `CreateBar'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:11000: in function `Start'
[string "@Interface\AddOns\DBM-PvP\PvPGeneral.lua"]:600: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:892: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:879>

Locals: (*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = 0
(*temporary) = 0

**Comment by amk0** [comment] 2021-02-24 20:12
Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1557: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_2:SetPoint.
Time: Wed Feb 24 20:25:36 2021
Count: 405
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1557: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1557: in function `Enlarge'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1159: in function `Update'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1610: in function <Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1604>

Locals: (*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = 0
(*temporary) = 0

**Comment by QartemisT** [comment] 2021-02-24 20:12
Are you running DBM-PvP r116?

**Comment by amk0** [comment] 2021-02-24 20:13
`Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1557: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DBT_Bar_2:SetPoint.
Time: Wed Feb 24 20:25:27 2021
Count: 68
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1557: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DBT_Bar_2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1557: in function `Enlarge'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1159: in function `Update'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1610: in function <Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1604>

Locals: (*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = DBT_Bar_3 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = 0
(*temporary) = 0
`

**Comment by amk0** [comment] 2021-02-24 20:14
> Are you running DBM-PvP r116?

Yes

r116 for DBM PvP Mods
r138 for DBM Challenges
9.0.21 for DBM
r128 for DBM SpellTImers2

**Comment by QartemisT** [comment] 2021-02-24 20:23
Could you go into /dbm, options, profiles, and grab me your export string please :)

**Comment by amk0** [comment] 2021-02-24 20:37
THere ya go:

`fIvtmUrsv4XYbLGqImJZKFxbBacs7cKvmTNjzveWg)7ytSNzITNmZGIiDz3LD1mT7QuvD7zNioGcG0EaqOrCIdiKveNqcPCB5uKfsCGlJm3ajy1CNCWs75L3R6UDB7XgSugzxD1V6vV333379sI7j7A7A3LiUw)WVSdxv6Hn)Jx8F(4nEPr(SnUg8NQFuQxuK76v3(50Vu)s(DOnS7sLh8lU4lk3I7wH22ZSzWsjobxPMDhMhBqoh7wh2Gj5(Dymzd6h65lPI7u21JkBtArFAnITvrjPBW3UBwI8ULe3TOTJZWcFOG4ATR4iI0sz2xB9D42UEnZUDJgBxT2E2wESFZLpBS7e80Cf2QrHA9rBSRamOIf4z7x6H)CRQFYslTuT6cI8qZ47X(jErrhIIb7M1h(Z(B3UTI6L4KT4WVksSOStVWh9xfxjpgdy8JksK7rKU2UDuMIBuxqBztCcxrBPmocMXoj)2Vx6rrVtjFRQeHbBugNJihR2XHC8t42TOmXvWhxpYGLDZXiEMILRrC7q1bNAelI8GsV283(DV9slLqSmAZAuLhxsXOTIjUw0XSfSFHdXl6bRKd2uDspQvnApBLn399xkf5x9FE8x7vXhW(LE9p9c)ThcXMjweoqYx8V8A8aVoenHuMoVj9fEBX9O4bXguWL00HwLBrD(FeksJHI17Nrk5hPZsgn2ENr6RmAMYUObnhwKCin7EpHkr3KDwz32CTNOFLtVS46f6rHBj331QQVYUvoE3M2UulM46Z5GZXDmEqs8K3iH4kHpb9gstQNDlIJ5RI2oe7gO8a4gG1WFCsogT1HBsjsZrtBzis9oR87Wi1z7XLowz5kvghQ0J9QOmWonmy9RY7ztv1Pu32x4DnVW30uSYg3pDdg921DiDUDrUSd1C09wZaxc8uBf1VR5l)gMFfZbOrESp1hU3c48HFLXXjmQOmpjpTPFhmIZeVv0z2Ga2ZlJRleBAr7crPfKnY7ljBKCi(o1OaJ3cmRP4QZStWQGpfe8UFcrQXzcTiG3Xo0SBXDPILN4f0lFAgXkXjPcUDiDOgNMP)ydCqPhA9XVdcQobH561ePYxOyMDR04z5kLPXZkwlt1cJn9y1eZr7QOAZcVORl1PzvIcWJNJOaPOF8V8p97rWCW1ujih5AEwSFTNTa80HJDk4UQsiUzaXutgfuQ1JafeT8GbBqa(pVTsqDWWfSNn9TDSQsvk4kcSzFfRFLI5l4coxl6Id(RPPcNfdw2IxoptKQKTfDtIuAR4Un4Wntzok(IfWasDoRQTcXIFeOaOVFAEr1J9y2Tc8ztXvqtJ40cDbwM2CgM93ANmG3Gc6poyhB38hrB5z3JQ0BXCwof4Tspuc3CcNh)95zFHvkm2Cr8YnEagfmsMuCfiPowYQeWa5TBBksb8d)UQWOlEuUSa5ICGfuGf4YfR2SUoelwotXhvIsC8yHBaIYqge1R05U6EepFuHCNg5auHhuNIQyChlJVG4MZ1VHnzKuS8mIHgIvBaoEr4Fyuohhmb4WIvJbC59Hej3n7MvbcY151YKoIQMdO0(DrFsXgPpb8D1fgmY(iUJN4Qz894zA1Ik80UDz3E2Eu2OaL39Yc5Fj4IMNeQUQ2hu7Mj1H(WLE73iZuwdOxm6mDYXeV48TifMbMP(0O6EsBrDQShvULgVS6Co01V0D(EIRhJxgFddaoZ7vsl(wX9hKXYABx1tHoqUlwh7PkChQNMXwwIlDFpENo9dtP1lUpl7M7wgkZF0oFQUQ1IUKA8X9fRCowmispTshaIV5IWWPFqYejggUOgrQ((3lLS0h8p(b6pP6GhZ7NQzPp4nFz9h9tFZpu)jvN4V2mb8KK4kFYY6ptSYF(w6pOvc)Q4wrHZP9ROi68k0niCXqzKZY6WBDiwZfbpawkhJRObOUDiToeaPRoNl9gMbfCWwxMtIJns3gG(7pH44tRPHqZuafkaC4V(o)7p7Z(mu422Aki6D)xdqPOgafYZwaCZvNrBpshCLOyW48fdikw9qTxlKW4W7GKrGvniNp0Oux9baQ8ReBXDfwGOJsMbGWq6FGUMDa524KTDDoUiw35SaIaYB0SHxeDrYV8unIPTlRFDBhugwxEEHQiPV4WACaZcpw38aKGyyTfjQjbcb6mX2GBH7ypJxLN2M474H(KyLk8o4xGcWnK29aZBg0ykMwMGHXwO(4g6EIMfxJmdpOddOT11GNQzhbfWdPht1sAfaabnEnAIQ06PaMCp6q(AzD1Dkubc1UToESi7lV8Ozkx8UIuXkMpXUfeup2qK7)Ryq4wFA9UCUhRARnLCEp6Za942a4g1iwOsGUf91hubk3g1DCIxaIirWSvRt98qrVjReD(7OXP)HfNR34IZLmT(yG0(jgOrZuVWw2Vrw7ozLWDHkJkt0GJCf2Sc7r85PlCiHOd0farC1iwIUl1qtbhWY1OT4sleffssGkJHBfQhl1GDK9fPTQRugcrzJRqmnI5viTdB2I7AzkULovI19oFhjOmnid8Od(4Fc0K2Krt9Fu1KivpWLqq94Bh4sVL(6mo(STlodabA(KaTGdfQMk8GXtZHtjPF6AlKwO7mlDaWhiCuIxeW)SahhQYFi(UMXrRyxh6J4CnLnz9eTGn1P95CYqVAbvzwhQYKCUaO1MWnWSyusBEnJHTMpOrPY5E0272Os5Tkep5WCS8SnIKUza1Ar(4ApizsyiHXZdTfm3uWmrXJWvbMttLagU2QC(GNTygZ6FoX1IB6PO0M6oURNjYSbJjVqRSwsXn1nvJv4H96a6YDI08NF3kBCJeF6WHbKrxRdOooizr35I9ZFozSo48shgMNaW6suSKXp7Rp3TKoUhTdC(8YGg4SmJhocMC5O)EzGtSekcP))34cgIvcqFqQaMnv2To54579gx6782NfqcfohRxYC401cfRGrey2sLxunwZrZmunocxTk1OeRJ1tbhyiXQHCajCrIAfegJqpmAfApQtYHqYvdcdYVJIZ9b1keF1icDyDR5ChamDjQJimshoZ7f)Vd`

**Comment by Molkree** [comment] 2021-02-28 21:54
```
1x DBM-StatusBarTimers\DBT.lua:1514: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_17680_2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@DBM-StatusBarTimers\DBT.lua"]:1514: in function `SetPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@DBM-StatusBarTimers\DBT.lua"]:813: in function `CreateBar'
[string "@DBM-Core\DBM-Core-9.0.21-9-gaa42598.lua"]:11003: in function `Start'
[string "@DBM-PvP\Battlegrounds\SeethingShore.lua"]:75: in function `handler'
[string "@DBM-Core\DBM-Core-9.0.21-9-gaa42598.lua"]:892: in function <DBM-Core\DBM-Core.lua:879>

Locals:
(*temporary) = DBT_17680_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_17680_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0
```

DBM-PvP is r116.

List of other addons:

- AllTheThings
- BugGrabber
- BugSack
- Transcriptor
- Wowhead Looter
- DBM and most of its modules

**Comment by QartemisT** [comment] 2021-02-28 22:34
> ```
> 1x DBM-StatusBarTimers\DBT.lua:1514: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_17680_2:SetPoint.
> [string "=[C]"]: in function `SetPoint'
> [string "@DBM-StatusBarTimers\DBT.lua"]:1514: in function `SetPosition'
> [string "@DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
> [string "@DBM-StatusBarTimers\DBT.lua"]:813: in function `CreateBar'
> [string "@DBM-Core\DBM-Core-9.0.21-9-gaa42598.lua"]:11003: in function `Start'
> [string "@DBM-PvP\Battlegrounds\SeethingShore.lua"]:75: in function `handler'
> [string "@DBM-Core\DBM-Core-9.0.21-9-gaa42598.lua"]:892: in function <DBM-Core\DBM-Core.lua:879>
> 
> Locals:
> (*temporary) = DBT_17680_2 {
>  0 = <userdata>
>  obj = <table> {
>  }
> }
> (*temporary) = "TOP"
> (*temporary) = DBT_17680_2 {
>  0 = <userdata>
>  obj = <table> {
>  }
> }
> (*temporary) = "BOTTOM"
> (*temporary) = 0
> (*temporary) = 0
> ```
> 
> Got it even before bg start in Seething Shore, either when it was 30 seconds before start or when 2 timers for first nodes started.
> 
> DBM-PvP is r116.
> 
> List of other addons:
> 
> * AllTheThings
> * BugGrabber
> * BugSack
> * Transcriptor
> * Wowhead Looter
> * DBM and most of its modules

See if the latest alpha of dbm-pvp fixes this exact issue.

**Comment by Molkree** [comment] 2021-03-02 16:12
@QartemisT, I've updated to the latest alpha.
Hit this bug again in Battle of Gilneas, in my experience, it happens there the most, maybe in every other match or 1/3.
Got the first error when timer for mines should have appeared:
![image](https://user-images.githubusercontent.com/12860284/109676938-37fd9100-7b8a-11eb-8ac1-c69d0e807577.png)
```
6x DBM-StatusBarTimers\DBT.lua:1515: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_4:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@DBM-StatusBarTimers\DBT.lua"]:1515: in function `SetPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@DBM-StatusBarTimers\DBT.lua"]:813: in function `CreateBar'
[string "@DBM-Core\DBM-Core-9.0.21-12-gc742b1e.lua"]:11003: in function `Start'
[string "@DBM-PvP\PvPGeneral.lua"]:600: in function `handler'
[string "@DBM-Core\DBM-Core-9.0.21-12-gc742b1e.lua"]:892: in function <DBM-Core\DBM-Core.lua:879>

Locals:
(*temporary) = DBT_4 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_4 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0
```
After that it only got worse, more errors and timers overlaid on top of each other. Attaching other 2 errors that appeared later but not sure they'll be of any help without the root cause.
```
2x DBM-StatusBarTimers\DBT.lua:1515: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DBT_4:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@DBM-StatusBarTimers\DBT.lua"]:1515: in function `SetPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:524: in function `Append'
[string "@DBM-StatusBarTimers\DBT.lua"]:958: in function `SetElapsed'
[string "@DBM-StatusBarTimers\DBT.lua"]:752: in function `CreateBar'
[string "@DBM-Core\DBM-Core-9.0.21-12-gc742b1e.lua"]:11003: in function `Start'
[string "@DBM-PvP\PvPGeneral.lua"]:600: in function `handler'
[string "@DBM-Core\DBM-Core-9.0.21-12-gc742b1e.lua"]:892: in function <DBM-Core\DBM-Core.lua:879>

Locals:
(*temporary) = DBT_4 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_3 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0
```
```
126x DBM-StatusBarTimers\DBT.lua:1534: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_4:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@DBM-StatusBarTimers\DBT.lua"]:1534: in function `MoveToNextPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:559: in function `Remove'
[string "@DBM-StatusBarTimers\DBT.lua"]:1220: in function `RemoveFromList'
[string "@DBM-StatusBarTimers\DBT.lua"]:1160: in function `Update'
[string "@DBM-StatusBarTimers\DBT.lua"]:1612: in function <DBM-StatusBarTimers\DBT.lua:1606>

Locals:
(*temporary) = DBT_4 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_4 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0
```

**Comment by MysticalOS** [comment] 2021-03-08 20:40
Just want to respond that this isn't being ignored. there is a test branch that's in progress https://github.com/DeadlyBossMods/DeadlyBossMods/tree/dbt to address this and other stuff. updating some old code to better code so whatever blizz changed to cause these issues to start happening, stops happening with more robust codebase.

it's not ready for primetime use yet but experienced coders/debuggers can run it and give feedback here https://github.com/DeadlyBossMods/DeadlyBossMods/issues/519

**Comment by MysticalOS** [comment] 2021-03-11 01:36
Pushed DBT rewrite ahead of schedule. it has some quirks but it should in theory solve all of these issues. in current alpha, for testing.

**Comment by QartemisT** [comment] 2021-03-13 23:38
Closing this issue in favor of #519, where we will keep track of all future DBT issues and updates.

**Closed by QartemisT** 2021-03-13 23:38 UTC
Labels: question, ⚠️ High Priority
