### ISSUE TITLE
SetPoint failed because Cannot anchor to a region dependent on it.

### ISSUE THREAD

**Issue by cwagrant** [DeadlyBossMods/DeadlyBossMods#524] opened 2021-03-12 04:40 UTC
**Describe the bug**
During the Mythic Council of Blood fight in the very last phase received the error:

"Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1515: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from DBT_6:SetPoint.

**Do you have an error log of what happened?**
no

**To Reproduce**
Was not consistently happening during the fight to all of our raiders, but many of them kept crashing with this error. Mostly in the very last phase.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but multiple people all reported having the same issue in the raid and resolved it by disabling DBM for the fight.

**Which version of DeadlyBossMods are you using?**
The most recent as of 3/11/2021.

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by MysticalOS** [comment] 2021-03-12 04:56
Duplicate of https://github.com/DeadlyBossMods/DeadlyBossMods/issues/506

Might also be fixed in latest alpha

**Closed by MysticalOS** 2021-03-12 04:56 UTC
Labels: duplicate
