### ISSUE TITLE
Lua error when receiving any whisper

### ISSUE THREAD

**Issue by mbattersby** [DeadlyBossMods/DeadlyBossMods#1341] opened 2024-10-24 02:05 UTC
**Describe the bug**

Get a Lua error from DBM-Core when receiving any whisper inside checkForSafeSender.

The error is due to `GetNumGuildMembers()` only returning 2 values and no value for `numOnlineAndMobileMembers`.

**Do you have an error log of what happened?**

```
3x DBM-Core/DBM-Core.lua:678: 'for' limit must be a number
[string "@DBM-Core/DBM-Core.lua"]:678: in function <DBM-Core/DBM-Core.lua:636>
[string "@DBM-Core/DBM-Core.lua"]:7191: in function <DBM-Core/DBM-Core.lua:7189>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1082: in function <DBM-Core/DBM-Core.lua:1069>

Locals:
sender = "Tandemic"
checkFriends = true
checkGuild = true
filterRaid = true
isRealIdMessage = false
totalMembers = 532
_ = 3
numOnlineAndMobileMembers = nil
scanTotal = nil
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = "App"
(*temporary) = <table> {
 isFriend = true
 isDND = false
 isFavorite = false
 gameAccountInfo = <table> {
 }
 accountName = "|Kp27|k"
 battleTag = "Schnell#1882"
 note = ""
 rafLinkType = 0
 bnetAccountID = 29
 appearOffline = false
 customMessage = ""
 lastOnlineTime = 1729161649
 customMessageTime = 0
 isAFK = true
 isBattleTagFriend = true
}
(*temporary) = <table> {
 isGameAFK = false
 clientProgram = "App"
 richPresence = "In App"
 isGameBusy = false
 gameAccountID = 63
 isInCurrentRegion = true
 regionID = 1
 hasFocus = true
 canSummon = false
 isOnline = true
}
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
DBM = <table> {
 DungeonMusic = <table> {
 }
 ReleaseRevision = 20241022000000
 TaintedByTests = false
 Arrow = <table> {
 }
 RangeCheck = <table> {
 }
 Test = <table> {
 }
 Voices = <table> {
 }
 BattleMusic = <table> {
 }
 InfoFrame = <table> {
 }
 Flash = <table> {
 }
 ModLists = <table> {
 }
 Difficulties = <table> {
 }
 Music = <table> {
 }
 classicSubVersion = 0
 HighestRelease = 20241022000000
 registeredUnitEvents = <table> {
 }
 VoiceVersions = <table> {
 }
 AddOns = <table> {
 }
 Options = <table> {
 }
 Revision = 20241022110915
 shortTermRegisterEvents = <table> {
 }
 Defeat = <table> {
 }
 DefaultOptions = <table> {
 }
 Victory = <table> {
 }
 Counts = <table> {
 }
 Nameplate = <table> {
 }
 HudMap = <table> {
 }
 DisplayVersion = "11.0.23"
 Mods = <table> {
 }
}
```

```
Dump: value={ GetNumGuildMembers() }
[1]={
  [1]=532,
  [2]=2
}
```

**To Reproduce**

1. Receive a whisper.
2. Collect error.

**Screenshots**

N/A.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No.

**Which version of DeadlyBossMods are you using?**

```
<DBM> Boss Mod - Versions
Tankini: DBM 11.0.23 (2024/10/22 11:09:15) 
---
Found 1 player(s) with DBM & 0 player(s) with Bigwigs
Following 0 player(s) have outdated boss mod version: None
```

**Was it working in a previous version? If yes, which was the last good one?**

I believe this started with 11.0.5 release this week.

**Additional context**

I'm in a guild. There's nothing weird about it that I can see.

**Comment by MysticalOS** [comment] 2024-10-24 02:12
This was already fixed in alpha yesterday, I just haven't made a new release yet. I just did further fix to it though (I silenced errors yesterday but figured out root cause was an api change today)

**Comment by mbattersby** [comment] 2024-10-24 02:22
Thanks. Apologies I only looked through the main branch when I was checking if it had been fixed.

**Comment by b-morgan** [comment] 2024-10-24 17:56
Probably not needed at this point but this puts me on the watch list for this issue.
```
4x DBM-Core/DBM-Core.lua:678: 'for' limit must be a number
[string "@DBM-Core/DBM-Core.lua"]:678: in function <DBM-Core/DBM-Core.lua:636>
[string "@DBM-Core/DBM-Core.lua"]:7191: in function <DBM-Core/DBM-Core.lua:7189>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1082: in function <DBM-Core/DBM-Core.lua:1069>

Locals:
sender = "Alcyon"
checkFriends = true
checkGuild = true
filterRaid = true
isRealIdMessage = false
totalMembers = 20
_ = 1
numOnlineAndMobileMembers = nil
scanTotal = nil
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = "App"
(*temporary) = <table> {
 isFriend = true
 isDND = false
 isFavorite = false
 gameAccountInfo = <table> {
 }
 accountName = "|Kp2|k"
 battleTag = "Elensar44#1853"
 note = ""
 rafLinkType = 0
 bnetAccountID = 1
 appearOffline = false
 customMessage = ""
 lastOnlineTime = 1729699951
 customMessageTime = 0
 isAFK = false
 isBattleTagFriend = false
}
(*temporary) = <table> {
 isGameAFK = true
 clientProgram = "App"
 richPresence = "In App"
 isGameBusy = false
 gameAccountID = 5
 isInCurrentRegion = true
 regionID = 1
 hasFocus = true
 canSummon = false
 isOnline = true
}
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
DBM = <table> {
 DungeonMusic = <table> {
 }
 ReleaseRevision = 20241022000000
 TaintedByTests = false
 Arrow = <table> {
 }
 RangeCheck = <table> {
 }
 Test = <table> {
 }
 Voices = <table> {
 }
 BattleMusic = <table> {
 }
 InfoFrame = <table> {
 }
 Flash = <table> {
 }
 ModLists = <table> {
 }
 Difficulties = <table> {
 }
 Music = <table> {
 }
 classicSubVersion = 0
 HighestRelease = 20241022000000
 registeredUnitEvents = <table> {
 }
 VoiceVersions = <table> {
 }
 AddOns = <table> {
 }
 Options = <table> {
 }
 Revision = 20241022110915
 shortTermRegisterEvents = <table> {
 }
 Defeat = <table> {
 }
 DefaultOptions = <table> {
 }
 Victory = <table> {
 }
 Counts = <table> {
 }
 Nameplate = <table> {
 }
 HudMap = <table> {
 }
 DisplayVersion = "11.0.23"
 Mods = <table> {
 }
}
```

**Closed** 2024-10-26 00:18 UTC
