### ISSUE TITLE
Wrathion mythic slow stack track

### ISSUE THREAD

**Issue by tharakadesilva** [DeadlyBossMods/DeadlyBossMods#131] opened 2020-02-02 03:00 UTC
**Is your feature request related to a problem? Please describe.**
If we go over 50 stacks without getting a Hand of Freedom, Tiger's Lust or some sort of clear, you are going to be killed.

**Describe the solution you'd like**
In mythic Wrathion we have to track the slow debuff. Spell ID of the debuff is 313255.

**Comment by MysticalOS** [comment] 2020-02-02 05:44
It looks like the issue is just stuff isn't in combat log. I don't really want to scan unit aura just for player warnings. I'll probably just scrap player warnings and use infoframe to track stacks instead in P1

**Comment by tharakadesilva** [comment] 2020-02-02 06:06
Yeah, scanning unit auras for each player would be superfluous. I was thinking of showing everything in infoframe too, is that an inefficient change?

**Comment by MysticalOS** [comment] 2020-02-02 06:12
I mean yes and no. not by todays standards, a million other addons (like details) using 23526 x more cpu. but inefficient in sense of things dbm normally does. But it'll be fine, it's wrathion.

**Comment by tharakadesilva** [comment] 2020-02-02 06:15
:D okay. It was a real issue in our group to see who was having closer to 50 stacks, so I feel that this would be really useful. Thanks @MysticalOS!

**Comment by MysticalOS** [comment] 2020-02-04 21:18
Closing since I think infoframe should cover this. although reopen if infoframe doesn't work :D

**Closed by MysticalOS** 2020-02-04 21:18 UTC
