### ISSUE TITLE
Trojan Virus found during update for alpha and release version

### ISSUE THREAD

**Issue by Wrrah** [DeadlyBossMods/DeadlyBossMods#645] opened 2021-08-18 19:01 UTC
**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment] 2021-08-18 19:55
duplicate of https://github.com/DeadlyBossMods/DeadlyBossMods/issues/643

There was no virus just a windows defender error. that file was perfectly safe but also replaced with a new one just to change the file hash.

Can read more about it here:
https://www.patreon.com/posts/dbm-9-1-9-false-55047651

**Closed by MysticalOS** 2021-08-18 19:55 UTC
Labels: duplicate

**Comment by Wrrah** [comment] 2021-08-18 20:37
thx for clearing this up
