### ISSUE TITLE
Error when entering dungeons

### ISSUE THREAD

**Issue by deathkok** [DeadlyBossMods/DeadlyBossMods#291] opened 2020-08-09 04:46 UTC
**Twitch client installed classic/retail version on retail/classic**
retail 8.3.30-16-g8906731
--

**Describe the bug**

When I enter dungeons I sometimes randomly get this error 

**Do you have an error log of what happened?**

Message: Interface\AddOns\DBM-Core\DBM-Core.lua:6481: attempt to compare number with nil
Time: Sat Aug  8 21:37:14 2020
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:6481: attempt to compare number with nil
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:6481: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:6480>
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:6489: in function `StartLogging'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4022: in function `func'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:1818: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:1809>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
LastInstanceMapID = 1594
difficultyModifier = nil

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes
**Which version of DeadlyBossMods are you using?**
8.3.30-16-g8906731
**Was it working in a previous version? If yes, which was the last good one?**
yes,8.3.30-13-g2f0682a
**Additional context**

**Comment by MysticalOS** [comment] 2020-08-09 04:53
Duplicate of bug #286

**Closed by MysticalOS** 2020-08-09 04:53 UTC
