### ISSUE TITLE
Tried to update to latest release for DBM and get a severe Trojan alert

### ISSUE THREAD

**Issue by Orbitus2001** [DeadlyBossMods/DeadlyBossMods#647] opened 2021-08-19 05:54 UTC
**Describe the bug**

I was trying to update to the latest version

**Do you have an error log of what happened?**

No error log that I can find
**To Reproduce**

To reproduce, all I had to do was keep trying to update from Curseforge.  Every time I did, it kept being flagged by my Windows Defender.
**Screenshots**
https://imgur.com/a/YS9vjYW

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Not applicable as far as I can see.
**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment] 2021-08-19 06:01
read this:
https://www.patreon.com/posts/dbm-9-1-9-false-55047651

if you don't want to read whole thing skip to bottom where it says "update 1" on how to fix it. Closing as duplicate of https://github.com/DeadlyBossMods/DeadlyBossMods/issues/646 https://github.com/DeadlyBossMods/DeadlyBossMods/issues/645 and https://github.com/DeadlyBossMods/DeadlyBossMods/issues/643

**Closed by MysticalOS** 2021-08-19 06:01 UTC

**Comment by Orbitus2001** [comment] 2021-08-19 06:04
Sorry, didn't see the post that is at the top of the list now.
