### ISSUE TITLE
DBM-StatusBarTimers in Arathi Basin

### ISSUE THREAD

**Issue by handy142** [DeadlyBossMods/DeadlyBossMods#478] opened 2021-01-13 20:47 UTC
**Twitch client installed classic/retail version on retail/classic**

Wow retail 

**Which version of DeadlyBossMods are you using?**

DBM-Core-9.0.17-21-ge101062.zip
DBM-PvP-r105.zip

**Describe the bug**

was in Arathi Basin and got this error (a lot)

3940x DBM-StatusBarTimers\DBT.lua:1532: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_1:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@DBM-StatusBarTimers\DBT.lua"]:1532: in function `MoveToNextPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:559: in function `Remove'
[string "@DBM-StatusBarTimers\DBT.lua"]:957: in function `SetElapsed'
[string "@DBM-StatusBarTimers\DBT.lua"]:890: in function <DBM-StatusBarTimers\DBT.lua:886>
[string "=(tail call)"]: ?
[string "@DBM-PvP\PvPGeneral.lua"]:433: in function `UpdateWinTimer'
[string "@DBM-PvP\PvPGeneral.lua"]:632: in function `handler'
[string "@DBM-Core\DBM-Core-9.0.17-21-ge101062.lua"]:896: in function <DBM-Core\DBM-Core.lua:883>

Locals:
(*temporary) = DBT_Bar_1 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_Bar_1 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0

**Comment by QartemisT** [comment] 2021-01-13 20:48
Duplicate of #476. Please watch tracking there for more information and updates on this issue.

**Closed by QartemisT** 2021-01-13 20:48 UTC
