### ISSUE TITLE
I don't have a target each time i log in

### ISSUE THREAD

**Issue by N30Exca** [DeadlyBossMods/DeadlyBossMods#405] opened 2020-12-03 11:19 UTC
Each time i log in a character in SL i get prompted by the i don't have a target sound queue, im 100% sure is DBM, i tryed disable all addon i use and then enable them one by one and the only 1 causing the issue was DBM, is not game breaking just lil anoying.

**Comment by MysticalOS** [comment] 2020-12-06 17:46
if it's being caused by DBM it's probably a 3rd party module like DBM-Interrupts

None of 1st party packages should cause this. I'd like a full list of DBM modules you have installed.

**Comment by N30Exca** [comment] 2020-12-06 18:34
just DBM CORE

**Comment by N30Exca** [comment] 2020-12-06 18:35
DBM CORE, Option GUI, Status Bar Timer, CastelNathria, Dungeon SL and Word Boss SL

https://imgur.com/gpwav8k

**Comment by QartemisT** [comment] 2020-12-06 18:37
And what is the EXACT message that you recieve? (Screenshot if possible?)

**Comment by N30Exca** [comment] 2020-12-06 18:51
No message my char say i do not have a target each time i log if dbm is active

https://streamable.com/s3hmbu

**Comment by Marlamin** [comment] 2020-12-06 23:09
This happens to me without any addons enabled at all, so don't think this issue is caused by DBM.

**Comment by MysticalOS** [comment] 2020-12-06 23:11
After conferring with other users and reading forums such a https://eu.forums.blizzard.com/en/wow/t/you-have-no-target-at-connection/218528. I agree this has nothing to do with DBM. Closing issue.

**Closed by MysticalOS** 2020-12-06 23:11 UTC
Labels: question
