### ISSUE TITLE
LUA Error with new BRD Raid

### ISSUE THREAD

**Issue by future-greg** [DeadlyBossMods/DeadlyBossMods#1344] opened 2024-10-26 17:30 UTC
Experiencing an LUA error with the new Timewalking BRD raid, seems to only occur during The Seven encounter - see below:

66x ...ddOns/DBM-Raids-Vanilla/BlackrockDepths/TheSeven.lua:201: attempt to index field '?' (a nil value)
[string "@DBM-Raids-Vanilla/BlackrockDepths/TheSeven.lua"]:201: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1082: in function <DBM-Core/DBM-Core.lua:1069>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1082: in function <DBM-Core/DBM-Core.lua:1069>

Locals:
Skipped (In Encounter)

**Comment by MysticalOS** [comment] 2024-10-26 17:57
Duplicate of https://github.com/DeadlyBossMods/DBM-Vanilla/issues/240

**Closed by MysticalOS** 2024-10-26 17:57 UTC
