### ISSUE TITLE
DBM 1.13.26-Classic interfering with Kui Nameplates

### ISSUE THREAD

**Issue by Ommand-** [DeadlyBossMods/DeadlyBossMods#100] opened 2019-12-31 02:20 UTC
**Describe the bug**
Since updating to 1.13.26 today DBM is interfering with my Kui Nameplates addon.  Basically it's causing the style of my nameplates to change depending on if the mob is selected or not.   I've disabled the "Boss mod communication" within Kui as well as checked "Do not show Namplate auras" within DBM to no effect.  

If I roll DBM back to .25 my nameplates return to normal.

**Comment by MysticalOS** [comment] 2019-12-31 02:34
it should have zero affect on KUI.

I even logged into classic and tested kui nameplates and had zero issues

**Comment by Ommand-** [comment] 2019-12-31 02:36
Whether it should or not is of little importance.  The only thing changing is the version of DBM.

**Comment by MysticalOS** [comment] 2019-12-31 02:38
it seems kui nameplates uses the old threat lib but does NOT embed it. DBM .26 removed that threat lib because it was abandoned by author and throwing errors. since DBM no longer has threat lib kui was using, threat features ceased working. this is a not a bug, that threat lib is not coming back into dbm unless it's updated.

DBM is newing a newer more up to date threat lib that fixes the bigs old one had. if KUI recieved an update supporting the new lib as well, that'll fix it's threat support. Closing this issue since if you want kesava to support the new threat lib you'll need to ask him over here https://github.com/kesava-wow/kuinameplates2

**Closed by MysticalOS** 2019-12-31 02:38 UTC
