### ISSUE TITLE
DBT rewrite bugs

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DeadlyBossMods#519] opened 2021-03-08 16:16 UTC
**Describe the bug**

- [x] Big timer (>10 seconds) moves downward on every (forced) update. Noticed it on the time to win timer in Battle of Gilneas. I don't mean natural ticking of the timer, only when it is updated forcefully.
- [x] Getting Lua error when calling `/dbm move`.
- [x] :AddTime and :RemoveTime and :Update on timers that are on small bars causes anchor to double for each bar update is called on. Doesn't break on large bars from testing. Then it infinitely sorts timers. If they are large and I run /run DBM:GetModByName(2426):TestAdd(10) test function on council, timers increase by 10 seconds without duplicating when moving back into small. but if I do it again when timers > 11 timers spawn duplicates and then infinitely sort. this problem goes away when sorting is disabled
 - [x] Small timers with offset of 0 and 0 for y and x overlap slightly. large/huge bars seem fine.
 - [x] Bar sorting when bars are paused breaks like fuck
 - [x] Bar animations moving from small to large don't work at all, They just float upward for a second instead of floating toward large bar anchor.
 - [x] When using simple timers (NoAnim) the animation still happens when it's not supposed to at all when using NoAnim mode.
 - [x] Turning on and off right and left icon options in bar appearance no longer live updates the icon correctly, since options stuff is not compliant with the changes to not allowing icons on both ends anymore. Personally the change to that should probably be reverted. No sense in taking away a configuration option. if a user wants icons on both sides let them.

**Comment by MysticalOS** [comment] 2021-03-08 20:56
The lua error for move and profiles should be fixed. Artemis forgot the load order and was creating upvalues for DBM-Core before DBM-Core was loaded (so was basically upvaluing nil)

**Comment by MysticalOS** [comment] 2021-03-08 21:41
My own issue I'm seeing is DBT.Options table is always nil. spam infinite lua errors when opening GUI.

**Comment by MysticalOS** [comment] 2021-03-09 04:08
:AddTime and :RemoveTime and :Update duplicates timers on top of adding time to them when they are small

If they are large and I run /run DBM:GetModByName(2426):TestAdd(10) test function on council, timers increase by 10 seconds without duplicating when moving back into small. but if I do it again when timers > 11 timers spawn duplicates and then infinitely sort

**Comment by SzRental** [comment] 2021-03-15 04:53
Bar Offset issues:

After DBT Rework small bars were overlapping and large bars were over spaced. 
![image](https://user-images.githubusercontent.com/80443021/111105036-62efc980-8528-11eb-9d4c-29f88f16be50.png)

Video Settings:
![image](https://user-images.githubusercontent.com/80443021/111105050-6edb8b80-8528-11eb-8c44-8fbacf0cf10f.png)

Bar Settings: 
![image](https://user-images.githubusercontent.com/80443021/111105071-7b5fe400-8528-11eb-9f3e-464854a4acbb.png)

The issue seems to be related to bar scaling. Setting both bars to 1 scaling:
![image](https://user-images.githubusercontent.com/80443021/111105132-a9452880-8528-11eb-88fa-c29944a71b36.png)

Image before DBT rework
![image](https://user-images.githubusercontent.com/80443021/111105156-b530ea80-8528-11eb-885a-6aba11398bba.png)

**Comment by MysticalOS** [comment] 2021-03-15 06:24
btw reviewing issue, molks unfixed issue might be same as my issue with update/add/remove caused weird ass behaviors. so it's possible it's already fixed. have him confirm that though. extremely odd movements of bar was caused by left over sort code existing from bluewiz still running in addition to yours, the random inserting/removing that was being done in SetElapsed event I removed.

**Comment by Molkree** [comment] 2021-03-15 11:12
Yes, long timer no longer moves downward on every update, forgot to mark it as fixed.

**Comment by MysticalOS** [comment] 2021-03-15 18:12
Turning on and off right and left icon options in bar appearance no longer live updates the icon correctly, since options stuff is not compliant with the changes to not allowing icons on both ends anymore. Personally the change to that should probably be reverted. No sense in taking away a configuration option. if a user wants icons on both sides let them.

**Comment by BluespiritWoW** [comment] 2021-03-16 00:37
DBM bar spacing before the changes. I will work on an image after the change.
![DBM SPACING](https://user-images.githubusercontent.com/31854759/111238784-30001100-85ce-11eb-8800-0b97b913f687.png)

**Comment by BluespiritWoW** [comment] 2021-03-16 00:46
DBM spacing issue after the rework. UI scale is off. Spacing looks to be 15 to 20 ish pixels off. and the anchor is also off.
![DBM SPACING ISSUE ](https://user-images.githubusercontent.com/31854759/111239332-52465e80-85cf-11eb-845c-0349c5dd08d3.png)

**Comment by QartemisT** [comment] 2021-03-16 16:21
@BluespiritWoW Could you send me your export string, so I can replicate this :)

**Comment by BluespiritWoW** [comment] 2021-03-16 19:45
> @BluespiritWoW Could you send me your export string, so I can replicate this :)

Do you want my Saved Variables? Is there an export string?

**Comment by BluespiritWoW** [comment] 2021-03-16 19:46
Found it

nMvxSnYvv4yCdDB3kiXjzt2TTuepGaH2vBMKSD1kq76FJnRDIXEYMSOa7mXZn(oSJN5Y8t21vcrvuFOQiKQI6dBFQf)acXtOiEbe)A4DcbbAPqlGfcHe0(Gf8aOQgoN7D(Zo2RyEikzM79Cp)(D(o3K4k2T0n1BPY(KD8)LQwofV()U6pPlPWzZq11iks5YiFo4hvE5gDR7QA7M1YWYUATK1Q3q1Gun5IxAL(f9AsYOA7K3uDhdIMclvEtdvBXlRsSBqmDRo5LV0IsRCyKqQLStEtnF5v86)5P4pzQBz7Is4(mvtTny3t1wZPmkm6Xd8oAhz9we7Qw6MUsYRxnuy5wnrT0gmQAYEOIfTQDYMFn581IzhLGZ9D(y4ZZEC0B3OuTKXwu6vlE9)YxL)0PGUHXgm0SO98T6TwF3DDiUjITJArMZaID1K9fcOCGZHEakfURS41)pV(R)MtmXeDGpC7tl0CGA8BQJpYXvo4OE4c8NoYK7h4zpmWzKo)a2sPmjZuWY0LDXsMUe7DvBq2oTMMLPZ2L3O02TiA6QBVlSaNT3tFhBRgKDUKR7U7lNJ0asqmMpMGZu86)Q3aF(wDc9ZBv8gTR8BVXetKOBwd9g3vMAB51KQ0jMJ6GarKjrumltYWxVA0RrR7xmd(mNTVg0owguMe7xqvJ7ivIS(mr5vG5cl3wNLnh(zfU3wKBW)1n11CPAp5ob6(x7D)5OUhTF48)oCN78XcKPZdHI3M)8oHlfJ5)ONbF(424z5ztyxiYjNXZ1f9YBwSKC(RU1v3hu66UTni7SMvAO2RxufdQmZxRot1(U04XF4a(N)r85TJxjcQYF)H4ZVFFmWwWqTzM1Smjr(WmjRXTZz)ir1BWUERVi)jEA7QX8CWk(NCZ5zIfYHx(Tph(mxn4GCO0b8kqcXB)L4pCvPU(lqM5GsnSmRP3K6QS)njeMiwfQhWwoUg(upkh62f)zt(x)g)miomG0HKAr4TTCBgrzFuWLj76Qe3cYew41nxBt1w6n4VxjOyDe1vG)zNIeudVy8cfWuFVpaFoPhSVNVGfGIjGHIc5zcRiJsKRLCFURb2en0ZHikrBB1KdGkas57j05yP2WX)32J)etiWlF3Vg)j2lHT)YIu0WkObk5rF8BXF(dD4(mRg3fWOpSKPHUjbFtSacI19WhGpVoBk0UZ654A1sS24EASGDnlyfybinQ4B1K7eee3ANhQaWzhn5RMyz2m5WmcQ19kOAVPQTPUzthA)0g3tTTtvd123YsVbHYoxWYwtTfHzO6skdhmSYnCivuDGQPBzz41coXsM7AvWgwfu2sEWM4jnIDZnpkB26ma9q1W)K5bOvOSfYP7GDSYcNrlvx9goR756aT9OSPaGA40QR2oTP2TjggWRYVh0hRg0bYQvfph9g0oPTTTUhV3Yrt1VokD8KlzUMLlrHnFG6uvoRLNPRM19mrhfTxOYZ3BNmRllVELY5liZMNFi1HLRXpJSwT2b0onkB6aPvJaDR1iylOnTSn0Yy54K2Gy7g83E7Ul)VvyZY3dXKVMnP6om(2kcM4MQUnOCDaenk2kckacGk)3TQNUHwfIJJAtmiGVkTHXTaHOpk)kxTx6mx(TypDGYkJLmUPnnHp1G0cSnhLdlUroFiYLoGcvEgy1himy9O9Q6w2QP)PcmbcDwCqfeZ8OCSPccLXE3mOaguJCuyZiIKY2qmpmZJnfehBs4ITMQMkc(N9R)btGzrZNXakr8nYnyAqAuvlMht54qnbs1DsGwVAl(IRPQR5lBf2CI0COil2RXJSmijZgTHEIGZ0Yq7LEk2cN(SGChEPWCNkau1Wdy9uUqU8MuvtCnZGrsm2MVfKXXvnjWI3CD5Y3uEt)9HYX0FTRVZxH0WvFpIJFOF(HIGuG9fVvzVOKxEo7WRmaHxQ4nU6cB)gNCY7FQvGvzGNALRvn5LVKuYKqaI4M1Z2gYcQOYw3SQNHHc78JCBq9IuY(qMcEiRVhX2MxxoxApxR0nAqyUCFtjZ90DH3VWiesopB1LsEyfR90jIKGARrajXMoQi7w6nCTSBZYoaFO1Ho1aN3lM1YMSTdUoNT9x521Bzz5sR0yvBlR9i3PGQ5UQ2Klz1SzhF4K6f2IYsfwYJwjhtuzSA5YOh65hNdCPRLmrI(vS0igcDw1WJuJhQoaCqCCxynOmwjrSIlPJEL(dkXBx8gl9Ip(loXepbB6OcarENJDAW3a5lSPqFmy62qQcxX5LlHPYCDG9PpLdRQTQ7fx6sxoWHLbqnr3sxrpe(2GQM55Wc2QMonaIzGlnOsVNi5dpqEgiBMkLQlxFO8yoi0nbw0bBRVVAfYhiETTOz34tpKqN2Y9QU6G1kxyelVgHruDxMEygltphr(0rFBwQG6eOdfN6gaW(i2p01j1PlAPXIAlE0Rms1fPTUiQUljWMZr2fKNVEtJ0JiJxHnDiIfhAKySlaShVaMQczOkrBgvRaJyuf8isBx5ILYEZ13qUCP1YVV)x3kbqXxRuorJi2Znwhq6wyDXKXJAzPQWwop6w410WFByqaRWpXK2pq9YkAKc5JCKj9x4fudDaXI68unPmMan4UOuLTSmC1zigCMSdJloTiuceq0asETGo(k9hQjm0BzUqS(bALcL5PLtpSitvKyW8FLp2(JZo3OXpjWQdJ9r4CJldqsKbKkgxeFGPiVurpnaEvIoEK1LN0Vzzq3PsIGqNiqFkcTWhvIN0Tcsz11lyeFFUaA7vFtrDn4hrWY6Q7bT9i7PJ28vNiL6R9G3zXdJImqBwNh7tHZyXwqq(ZVNnrdRPfOnXwpqJ06nN4JZx)y8ilXlHf2tnsdat2UDa2WXyB4mB6hdOhMTM8DcSGXH2kfGKc9rfFH7f2HaTLvbAGZm42eS)MneiEXRLmzIW)A5RLijiOyONvTC0DbL5kPaBR1jN8GF8ZUskWTCMjo7pyVj)x18ztEyuKqI2Rs2btWczwoeBhGrwb97NTC(nw3uWKIZyN2H3d0PoHy(jZTHY3)kavEy3FbpIhYTrzC(ILHopjpihzhVMy7NXJJUcmsZautXcMHt3bbk8TpFI4TGZB2eSmPJYfXPh6tz(NEF8Yqg2DZ3Xz(SpxibWO5lXze4FgsLnnjgsqFybu5GSVhUse1FmI8eSP8jQhYq7ZTVpbePZYo)4YxLODfqi5qqbdrPrzl1aEBkD4oWYa1dJKJ1dUOOtuuyFnRs58BwSQkGk4yzkBbJa5qpWFSdNBB8e9hS1L0PdrHW8GHZD6CiTkTDP6ne6D40o8w62Emxj2SYa2cWTHp5qwa)eDFSpbQE44AY267bNXiInq730fUzrIQHBaD7XwQXRvog6BW9J(ToMkO2jemCismqXYct8pasmF4oRvnn46Wa0xqm(vwqYoIr(h5qFlc1VqAs48Hfre0D3fu61i3ZjUN88Jh9CLjdZ(I4lpYJBzA0GVcxIFJ55IsMI9EASgpYE24qnhh2mmdXXTwnyXTytpCEkKEo7igZrA0tOjb1pbj2lEw28w1sVuWeAzH568AHiKqB3W6g(05s2acpK6OostDjq55iRBMbs3SXWEyE6wjoKxtuuyL2Pl5tRCucscoxQLdrCOvvBC3JY1Ty1OXLZiguEOuwCK714J0mktE5Z85(MbuvUDUPoUMfqthwMiN7yKWRHvtmxhS7mRUrjGptAMTUrbi1hgICU4dsh4RCOhgRi7))Ru1eVs1Wwesi7(J9fe)noF(RKANIx)94xm9hlvtez4QPSdVYo4Rjs1ewWxM)GFX)xd(I)DGLYojxs)WlWFWVe8R2jfzMyXCSRNa9EJSR3u4IRbPGqtEXDg1JZgcD7y8Mq7kc)8XuCOb5xlDwXDbGNZiIlW5jqIWzBZsb57pPukmHzi2jbYC5ZEOOzJdt9EMqL3qZYZZsEyIpB0vMe2yrX)wCI145dDakC(xbEW5lKEJYY3jBX0Y3PqT0vYl4gJQFOtYH2n2mLshSUPr7c8RWyCCuwwWrzAemhA6cwzeJ0yowUD8iOTT0KpIjlwI2Zhcq18U4Qu66ttfzU5q7ux3ar)59XNUSvtuTxdAQiGYJ47XjuTYyTLveFE(r3evI)FecaXJq14x(8l9u951ZiOoUZnLoegGr1ZWfvdrBAr8iKq)8JKbHL91sKi5((acahkLx9Za8d)O9hIxDXBS8R9D)PNCYj(CLJpTVeEbsdnUWIh976wgAVgqE9mp3w7d4a8CjB51RYbDMToX1fZiJ3Pqj6684xwzcF0c)XPIql6oiLrih)ug4dtuORaQXvuLXwiJEZm2wUuObPVKKTq(K0(rwqqgFVbrSFyIL6HqBqcIrB)6TPJfzwfGN3G9OgxvIEOqaomly3d1ryPDexgcB2GB(GpJGFAhixUNpNNzZtZ5abzHO3ktK4nr29Xch8F4uZglLHs4HVIwk7P5U2q3YGuDh2RIUr6XdChIDDCH2(Q2ACy7PRvg6QQ1gqFACxHtQ3Gd3OW5KWRnc5K0lkPAtDg2OgczikbXg7TeERerKlNEiF3Esq4jKiXq1pXJsb3Hrky8uVwdK6DMp1th7Mdw(Oxj6IxhriLEa3gxLOAhJxsbdY9JUfHWBuEnyv(mYs5hd4dNlcX0J9VFCIXUW4MXVPHGcWZZox0D1vWwhAEgCzDJrj9Zqhl83I8)9PXB6RmYM9Ra8BooOHnE39orGBllqVMdIU4vOQnyN)hrLaWCC6ydDlU9fKSRDdQkbLr7IETaEN2H)xWh(oMH0DJ)CcCy2EchpiC)RH9cJ2JWNxjEZgNNKnBuMhwzrSmZSALJYXN6atfdV48amEeSW3(6Z)NHwNydPXizjLdGQqX)8Rh7IG(cJpBRH7XF9bWSaL7B)F)1qH6JJyICa9FzP(rWE(zOt7V8kQ3ppGActCE2qhp)Ilw5)9

**Comment by QartemisT** [comment] 2021-03-22 10:22
As the last issue has been fixed as of #541, I am closing this issue till people report any further issues :)

Hurray, list is complete!

**Closed by QartemisT** 2021-03-22 10:22 UTC
Labels: ⚠️ High Priority, 🐛 Bug
