### ISSUE TITLE
Draenor garrison mod resets to default settings on update

### ISSUE THREAD

**Issue by TheCheat54** [DeadlyBossMods/DeadlyBossMods#391] opened 2020-11-20 02:18 UTC
The Draenor module's settings for garrison invasions seem to be resetting for me anytime it is updated. I have about 12 characters for which I've disabled the mod (and warnings, since unchecking "enable boss mod" wasn't working) in the past and the settings keep inexplicably returning periodically. The only regular change that could be happening is updates to the mod module since I check for updates at least once a day. The latest version I had this happen on was r53.

**Comment by MysticalOS** [comment] 2020-11-20 02:26
Can't reproduce this. Settings save correctly. They would have only reset once when DBM-GarrisonInvasions was merged with DBM-Draenor but that's it. Once you turn the off again they'll stay off.

Also, options are per character so you'd have to turn them off 12x, that's normal.

**Comment by TheCheat54** [comment] 2020-11-20 02:30
But I need to turn them off 12 times every couple of weeks? That's the behavior I'm seeing currently. It stayed fine for about 3 months until this randomly started occurring.

**Comment by MysticalOS** [comment] 2020-11-20 02:35
Can't reproduce that problem, they only reset once, this tuesday, no other time, unless you deleted wtf or it got corrupted/removed at some point in one of these patches.

**Comment by TheCheat54** [comment] 2020-11-20 02:54
Is it possible you'd been testing the reset in some earlier alphas? I'm on all alpha channels for nearly my entire addon set so that could possibly fit. It's happened three times:
Week of 9.0.1 (noticed that Thursday)
Last week's reset (noticed Friday)
This week (today)

**Comment by MysticalOS** [comment] 2020-11-20 02:57
on alpha channel you must have seen a reset in GarrisionInvasions maybe, before it was fully deleted. But you would have had to grab alpha at a specific hour. but outside of that I can't see any other reason

**Comment by QartemisT** [comment] 2020-11-27 14:48
Closing this issue as possible cause explained, and no response from author :)

**Closed by QartemisT** 2020-11-27 14:48 UTC
