### ISSUE TITLE
DBM saying it is classic version

### ISSUE THREAD

**Issue by wendyemdub** [DeadlyBossMods/DeadlyBossMods#96] opened 2019-12-04 23:09 UTC
I have only ever had the retail version installed but now it is telling me that it is for classic. I have reinstalled the correct addon and it still says it is meant for classic.

**Comment by MysticalOS** [comment] 2019-12-04 23:16
Duplicate of https://github.com/DeadlyBossMods/DeadlyBossMods/issues/74 , Twitch client installed wrong version on you, you'll have to remove and clean install correct DBM to fix this

**Closed by MysticalOS** 2019-12-04 23:16 UTC
Labels: duplicate, invalid, wontfix
