### ISSUE TITLE
DBM Pull Timer Not Showing Up

### ISSUE THREAD

**Issue by Lunarevel** [DeadlyBossMods/DeadlyBossMods#382] opened 2020-11-09 08:28 UTC
What I mean by the DBM pull timer not showing up, I mean the big numbers in the middle of the screen. The small bar on the side works and the voice countdown works, but the big numbers counting down are missing. My guildies have experienced the same thing, all 15 of them, so it isn't just me.

I am using the latest version of DBM and the pull timer worked on versions prior to the latest DBM update.

**Comment by QartemisT** [comment] 2020-11-09 11:47
Duplicate of #380.

Comment by MysticalOS: `the timer should still show, the numbered countdown has been removed from now because blizzard broke it and I'm waiting for blizzard to fix it before enabling it again.`

**Closed by QartemisT** 2020-11-09 11:47 UTC
